### ISSUE TITLE
shellen cannot start

### ISSUE THREAD

**Issue by mustakcsecuet** [merrychap/shellen#15]
Hi
I have tried to run shellen using both pip3 and source code installation, but failed in following:
```
Traceback (most recent call last):
  File "/usr/local/bin/shellen", line 11, in <module>
    load_entry_point('shellen==0.2.2', 'console_scripts', 'shellen')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/shellen/main.py", line 3, in <module>
    from shell import Shellen
  File "/usr/local/lib/python3.6/dist-packages/shellen/shell.py", line 9, in <module>
    from prompt_toolkit.styles import style_from_pygments, style_from_dict
ImportError: cannot import name 'style_from_pygments'
```
Following is system information:
`4.18.5 #1 SMP Tue Aug 28 16:08:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux`
and pygments is already installed.
![image](https://user-images.githubusercontent.com/1774620/44996383-a8090d00-af75-11e8-86d5-75055b23eada.png)

**Comment by merrychap** [comment]
Hmm, seems like some problems with `prompt_toolkit.styles` module. Give me a little time and I will try to figure it out (don't have enough time right now)

**Comment by mustakcsecuet** [comment]
Thanks. I appreciate it.

**Comment by merrychap** [comment]
[ywkw1717](https://github.com/ywkw1717) fixed the error. I merged his [pull request](https://github.com/merrychap/shellen/pull/16). So, it should work fine right now
